-- =============================================================================
-- 001_core_schema.sql — ArthaTrack relational core
-- Postgres 16. All money is NUMERIC(15,2) (never float: no binary rounding
-- drift on rupee amounts). All rates are NUMERIC(5,2) percent per annum.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid(), not used for ids
                                           -- but available for future token work

-- ---------------------------------------------------------------- enum types
DO $$ BEGIN
  CREATE TYPE user_role       AS ENUM ('individual', 'advisor');
  CREATE TYPE asset_type      AS ENUM ('gold','property','equity','mutual_fund','epf','ppf','fd','vehicle','cash','other');
  CREATE TYPE loan_type       AS ENUM ('home','vehicle','personal','education','gold','business','credit_card');
  CREATE TYPE interest_type   AS ENUM ('fixed','floating');
  CREATE TYPE loan_status     AS ENUM ('active','closed','defaulted');
  CREATE TYPE emi_status      AS ENUM ('pending','paid','overdue','waived');
  CREATE TYPE txn_type        AS ENUM ('income','expense','asset','loan');
  CREATE TYPE txn_source      AS ENUM ('manual','import','receipt');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------- users
CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name          TEXT        NOT NULL CHECK (length(trim(name)) > 0),
  email         TEXT        NOT NULL UNIQUE CHECK (email = lower(email) AND email LIKE '%_@_%._%'),
  password_hash TEXT        NOT NULL,
  role          user_role   NOT NULL DEFAULT 'individual',
  -- PAN: 5 letters, 4 digits, 1 letter (e.g. ABCDE1234F). Nullable: not every
  -- demo user supplies one, but when present it must be well-formed & unique.
  pan_number    CHAR(10)    UNIQUE CHECK (pan_number ~ '^[A-Z]{5}[0-9]{4}[A-Z]$'),
  advisor_id    BIGINT      REFERENCES users(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON COLUMN users.advisor_id IS 'Individual users may be assigned to an advisor; advisors have NULL here.';

-- --------------------------------------------------------------------- assets
CREATE TABLE IF NOT EXISTS assets (
  id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id        BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name           TEXT        NOT NULL CHECK (length(trim(name)) > 0),
  asset_type     asset_type  NOT NULL,
  purchase_value NUMERIC(15,2) NOT NULL CHECK (purchase_value >= 0),
  current_value  NUMERIC(15,2) NOT NULL CHECK (current_value  >= 0),
  purchase_date  DATE        NOT NULL,
  valuation_date DATE        NOT NULL DEFAULT CURRENT_DATE,
  notes          TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT assets_valuation_not_before_purchase CHECK (valuation_date >= purchase_date)
);

-- ---------------------------------------------------------------------- loans
CREATE TABLE IF NOT EXISTS loans (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id       BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  loan_type     loan_type     NOT NULL,
  lender        TEXT          NOT NULL CHECK (length(trim(lender)) > 0),
  principal     NUMERIC(15,2) NOT NULL CHECK (principal > 0),
  interest_rate NUMERIC(5,2)  NOT NULL CHECK (interest_rate > 0 AND interest_rate <= 60),
  interest_type interest_type NOT NULL DEFAULT 'fixed',
  tenure_months INTEGER       NOT NULL CHECK (tenure_months BETWEEN 1 AND 480),
  start_date    DATE          NOT NULL,
  status        loan_status   NOT NULL DEFAULT 'active',
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- --------------------------------------------------------------- emi_schedule
-- One row per installment. Generated by fn_generate_emi_schedule() (003).
CREATE TABLE IF NOT EXISTS emi_schedule (
  id                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  loan_id             BIGINT        NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
  installment_no      INTEGER       NOT NULL CHECK (installment_no > 0),
  due_date            DATE          NOT NULL,
  emi_amount          NUMERIC(15,2) NOT NULL CHECK (emi_amount > 0),
  principal_component NUMERIC(15,2) NOT NULL CHECK (principal_component >= 0),
  interest_component  NUMERIC(15,2) NOT NULL CHECK (interest_component  >= 0),
  closing_balance     NUMERIC(15,2) NOT NULL CHECK (closing_balance     >= 0),
  status              emi_status    NOT NULL DEFAULT 'pending',
  paid_date           DATE,
  UNIQUE (loan_id, installment_no),
  -- A paid installment must record when it was paid; an unpaid one must not.
  CONSTRAINT emi_paid_date_consistency
    CHECK ((status = 'paid' AND paid_date IS NOT NULL) OR (status <> 'paid' AND paid_date IS NULL))
);

-- --------------------------------------------------------------- transactions
CREATE TABLE IF NOT EXISTS transactions (
  id               BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id          BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  txn_type         txn_type      NOT NULL,
  amount           NUMERIC(15,2) NOT NULL CHECK (amount > 0),
  txn_date         DATE          NOT NULL,
  category         TEXT          NOT NULL DEFAULT 'uncategorized',
  description      TEXT,
  source           txn_source    NOT NULL DEFAULT 'manual',
  related_asset_id BIGINT        REFERENCES assets(id) ON DELETE SET NULL,
  related_loan_id  BIGINT        REFERENCES loans(id)  ON DELETE SET NULL,
  -- Dedupe key for CSV imports (Phase 3): hash of date|amount|description.
  import_hash      TEXT,
  created_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);
-- Amount is always positive; direction lives in txn_type. This keeps SUM()
-- aggregates unambiguous and lets CHECK (amount > 0) do real work.

-- -------------------------------------------------------- net_worth_snapshots
CREATE TABLE IF NOT EXISTS net_worth_snapshots (
  id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id           BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  snapshot_date     DATE          NOT NULL DEFAULT CURRENT_DATE,
  total_assets      NUMERIC(15,2) NOT NULL CHECK (total_assets      >= 0),
  total_liabilities NUMERIC(15,2) NOT NULL CHECK (total_liabilities >= 0),
  net_worth         NUMERIC(15,2) NOT NULL,
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
  -- One snapshot per user per day; the trigger in 004 upserts onto this key.
  UNIQUE (user_id, snapshot_date)
);

-- ------------------------------------------------------------- loan_products
-- Catalogue of what lenders offer. Not user data — seeded reference table that
-- the Phase 4 recommendation engine JOINs against.
CREATE TABLE IF NOT EXISTS loan_products (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  lender             TEXT         NOT NULL,
  product_name       TEXT         NOT NULL,
  loan_type          loan_type    NOT NULL,
  interest_rate_min  NUMERIC(5,2) NOT NULL CHECK (interest_rate_min > 0),
  interest_rate_max  NUMERIC(5,2) NOT NULL CHECK (interest_rate_max > 0),
  min_credit_score   INTEGER      NOT NULL CHECK (min_credit_score BETWEEN 300 AND 900),
  max_tenure_months  INTEGER      NOT NULL CHECK (max_tenure_months BETWEEN 1 AND 480),
  min_amount         NUMERIC(15,2) NOT NULL CHECK (min_amount >= 0),
  max_amount         NUMERIC(15,2) NOT NULL CHECK (max_amount > 0),
  processing_fee_pct NUMERIC(5,2) NOT NULL CHECK (processing_fee_pct >= 0),
  is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
  CONSTRAINT loan_products_rate_band  CHECK (interest_rate_max >= interest_rate_min),
  CONSTRAINT loan_products_amount_band CHECK (max_amount >= min_amount),
  UNIQUE (lender, product_name)
);

-- ------------------------------------------------------ credit_score_history
-- SIMULATED score. Derived entirely from this schema's own repayment data by
-- fn_compute_credit_score() (Phase 4). NOT a bureau (CIBIL/Experian) pull.
CREATE TABLE IF NOT EXISTS credit_score_history (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id       BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  score         INTEGER     NOT NULL CHECK (score BETWEEN 300 AND 900),
  computed_date DATE        NOT NULL DEFAULT CURRENT_DATE,
  factors_json  JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, computed_date)
);
COMMENT ON TABLE credit_score_history IS
  'Simulated in-app credit score derived from ArthaTrack repayment data. Not a credit bureau score.';
